import { readFileSync } from "node:fs";
import pg from "pg";
const env = Object.fromEntries(readFileSync(".env.local","utf8").split("\n").flatMap(l=>{const m=l.match(/^([A-Z0-9_]+)=(.*)$/);return m?[[m[1],m[2].replace(/^"|"$/g,"")]]:[]}));
const url = `postgresql://postgres.vwpudirxzaxhbczknaan:${encodeURIComponent(env.SUPABASE_DB_PASS)}@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres`;
const c = new pg.Client({ connectionString: url });
await c.connect();
const a = await c.query(`SELECT canonical_key, instrument_type FROM financial_instruments ORDER BY 1 LIMIT 6`);
console.log(a.rows.map(x=>x.canonical_key+" | "+x.instrument_type).join("\n"));
const b = await c.query(`SELECT canonical_key, ticker FROM instrument_listings ORDER BY 1 LIMIT 6`);
console.log(b.rows.map(x=>x.canonical_key+" | "+x.ticker).join("\n"));
await c.end();
